version: '3'

services:
  pushpin1:
    image: fanout/pushpin:1.35.0-1
    ports:
      - "7999:7999"
      - "5561:5561"
    platform: linux/amd64
    volumes:
      - ./routes:/etc/pushpin/routes  # Assuming the routes file is in the current directory and named 'routes'
    stdin_open: true
    tty: true

  pushpin2:
    image: fanout/pushpin:1.35.0-1
    ports:
      - "7998:7999"
      - "5560:5561"
    platform: linux/amd64
    volumes:
      - ./routes:/etc/pushpin/routes  # Assuming the routes file is in the current directory and named 'routes'
    stdin_open: true
    tty: true
