apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: pushpin
    deployment_tag: pushpin-001
  name: pushpin_deploy_001
  namespace: default
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: pushpin
      deployment_tag: pushpin-001
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: pushpin
        deployment_tag: pushpin-001
    spec:
      containers:
        - image: fanout/pushpin:latest
          imagePullPolicy: Always
          name: pushpin
          ports:
            - containerPort: 7999
              protocol: TCP
            - containerPort: 5561
              protocol: TCP
          resources:
            limits:
              cpu: 500m
              ephemeral-storage: 1Gi
              memory: 2Gi
            requests:
              cpu: 500m
              ephemeral-storage: 1Gi
              memory: 2Gi